### ISSUE TITLE
EnderStorage, ComputerCraft, Iron Chest: inventories broken: java.lang.AbstractMethodError at iq.a(EntityPlayer.java:603)

### ISSUE THREAD

**Issue by agaricusb** [agaricusb/MCPC-1.4.5#1]
EnderStorage compatibility with CPCM

cpcm-1.4.5-002.jar
mods/EnderStorage 1.3.0.3.jar
mods/Obsidiplates-1.1.0.2.zip
coremods/CodeChickenCore 0.6.14.jar

Place enderchest in the world, right-click to open
The chest opens (NSME was fixed in 002) but server crashes with:

2012-12-11 20:48:32 [INFO] [STDERR] 20:48:32 [INFO] Reloading Storage: 0|global. remote = false
2012-12-11 20:48:32 [INFO] [STDERR] 20:48:32 [INFO] Reloading Storage: 0|global. remote = false
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE] java.lang.AbstractMethodError
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at iq.a(EntityPlayer.java:603)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at rp.a(Container.java:48)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at codechicken.core.ServerUtils.openSMPContainer(ServerUtils.java:159)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at codechicken.enderstorage.EnderStorageManager.openChestGui(EnderStorageManager.java:559)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at codechicken.enderstorage.BlockEnderChest.a(BlockEnderChest.java:151)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at ir.a(ItemInWorldManager.java:473)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at iv.a(NetServerHandler.java:680)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at fl.a(SourceFile:58)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at cg.b(NetworkManager.java:289)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at iv.d(NetServerHandler.java:123)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at iw.b(ServerConnection.java:53)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at ht.b(SourceFile:30)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:637)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at ho.r(DedicatedServer.java:228)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:531)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE]   at fy.run(SourceFile:856)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE] Encountered an unexpected exception AbstractMethodError
java.lang.AbstractMethodError
    at iq.a(EntityPlayer.java:603)
    at rp.a(Container.java:48)
    at codechicken.core.ServerUtils.openSMPContainer(ServerUtils.java:159)
    at codechicken.enderstorage.EnderStorageManager.openChestGui(EnderStorageManager.java:559)
    at codechicken.enderstorage.BlockEnderChest.a(BlockEnderChest.java:151)
    at ir.a(ItemInWorldManager.java:473)
    at iv.a(NetServerHandler.java:680)
    at fl.a(SourceFile:58)
    at cg.b(NetworkManager.java:289)
    at iv.d(NetServerHandler.java:123)
    at iw.b(ServerConnection.java:53)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:637)
    at ho.r(DedicatedServer.java:228)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:531)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
    at fy.run(SourceFile:856)
2012-12-11 20:48:33 [INFO] [STDERR] 20:48:33 [SEVERE] This crash report has been saved to: /private/tmp/f2/./crash-reports/crash-2012-12-11_20.48.33-server.txt

More diagnostic information at https://gist.github.com/4264901

**Comment by agaricusb** [comment]
Same crash in ComputerCraft opening computer, reported by dw: http://technicraft.cz/crash-reports/crash-2012-12-12_07.35.47-server.txt
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/12/12 7:35 AM
Description: Exception in server tick loop

java.lang.AbstractMethodError
    at iq.a(EntityPlayer.java:603)
    at rp.a(Container.java:48)
    at cpw.mods.fml.common.network.NetworkRegistry.openRemoteGui(NetworkRegistry.java:315)
    at cpw.mods.fml.common.network.FMLNetworkHandler.openGui(FMLNetworkHandler.java:346)
    at qx.openGui(EntityHuman.java:1560)
    at dan200.ComputerCraft.openComputerGUI(ComputerCraft.java:213)
    at dan200.computer.shared.BlockComputer.a(BlockComputer.java:185)
    at ir.a(ItemInWorldManager.java:473)
    at iv.a(NetServerHandler.java:680)
    at fl.a(SourceFile:58)
    at cg.b(NetworkManager.java:289)
    at iv.d(NetServerHandler.java:123)
    at iw.b(ServerConnection.java:53)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:637)
    at ho.r(DedicatedServer.java:228)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:531)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
    at fy.run(SourceFile:856)

Looks like a Bukkit/Forge inventory incompatibility

**Comment by agaricusb** [comment]
MCPC+ supersedes CPCM -- if this issue reproduces with the latest build of MCPC+ please file a new issue on MCPC+
