### ISSUE TITLE
Secret Rooms Mod java.lang.NoClassDefFoundError: ModLoader

### ISSUE THREAD

**Issue by agaricusb** [agaricusb/MCPC-1.4.5#11]
CPCM build 004

Secret Rooms Mod http://www.minecraftforum.net/topic/546192-145v440secretroomsmodsmpforge-hide-your-diamonds-forever/ SecretRoomsMod-universal-4.4.0.144.zip

2012-12-15 00:07:56 [SEVERE] [ForgeModLoader] Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
2012-12-15 00:07:56 [SEVERE] [ForgeModLoader] 
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
    SuperSlopesCorners [SuperSlopes-Corners](1.4.4%285%29 SuperSlopes-4.6.zip) Unloaded->Constructed->Pre-initialized
    SuperSlopesIntCorners [SuperSlopes-IntCorners](1.4.4%285%29 SuperSlopes-4.6.zip) Unloaded->Constructed->Pre-initialized
    SuperSlopesSlopes [SuperSlopes-Slopes](1.4.4%285%29 SuperSlopes-4.6.zip) Unloaded->Constructed->Pre-initialized
    LegendaryBeasts [Legendary Beasts](Forge_LegendaryBeastsAlpha1.4.4.0.zip) Unloaded->Constructed->Pre-initialized
    gasmod [Gas mod](Gasmod v2.3.6.zip) Unloaded->Constructed->Pre-initialized
    NetherOres [Nether Ores](NetherOres_1.4.4.zip) Unloaded->Constructed->Pre-initialized
    ObsidiPlates [Obsidian Pressure Plates](Obsidiplates-1.1.0.2.zip) Unloaded->Constructed->Pre-initialized
    SecretRoomsMod [The SecretRoomsMod](SecretRoomsMod-universal-4.4.0.144.zip) Unloaded->Constructed->Errored
    bau5_ProjectBench [Project Bench]([1.4.4]ProjectBench-v1.4.zip) Unloaded->Constructed->Pre-initialized
    mod_CodeChickenCore [CodeChicken Core](coremods) Unloaded->Disabled
2012-12-15 00:07:56 [SEVERE] [ForgeModLoader] The following problems were captured during this phase
2012-12-15 00:07:56 [SEVERE] [ForgeModLoader] Caught exception from SecretRoomsMod
java.lang.NoClassDefFoundError: ModLoader
    at com.github.AbrarSyed.SecretRooms.SecretRooms.addrecipes(SecretRooms.java:204)
    at com.github.AbrarSyed.SecretRooms.SecretRooms.load(SecretRooms.java:172)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:440)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at mcpc.com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at mcpc.com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at mcpc.com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at mcpc.com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at mcpc.com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at mcpc.com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at mcpc.com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at mcpc.com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at mcpc.com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at mcpc.com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:81)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:344)
    at ho.c(DedicatedServer.java:58)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
    at fy.run(SourceFile:856)
Caused by: java.lang.ClassNotFoundException: ModLoader
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:141)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 32 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at codechicken.core.asm.ClassHeirachyManager.transform(ClassHeirachyManager.java:80)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:178)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:133)
    ... 34 more
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE] cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: ModLoader
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at cpw.mods.fml.common.LoadController.transition(LoadController.java:117)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at cpw.mods.fml.common.Loader.loadMods(Loader.java:493)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:81)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:344)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at ho.c(DedicatedServer.java:58)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at fy.run(SourceFile:856)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE] Caused by: java.lang.NoClassDefFoundError: ModLoader
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at com.github.AbrarSyed.SecretRooms.SecretRooms.addrecipes(SecretRooms.java:204)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at com.github.AbrarSyed.SecretRooms.SecretRooms.load(SecretRooms.java:172)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at java.lang.reflect.Method.invoke(Method.java:601)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:440)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at java.lang.reflect.Method.invoke(Method.java:601)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at mcpc.com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at mcpc.com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at mcpc.com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at mcpc.com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at mcpc.com.google.common.eventbus.EventBus.post(EventBus.java:268)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at java.lang.reflect.Method.invoke(Method.java:601)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at mcpc.com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at mcpc.com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at mcpc.com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at mcpc.com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at mcpc.com.google.common.eventbus.EventBus.post(EventBus.java:268)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   ... 5 more
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE] Caused by: java.lang.ClassNotFoundException: ModLoader
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:141)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   ... 32 more
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE] Caused by: java.lang.NullPointerException
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at org.objectweb.asm.ClassReader.<init>(Unknown Source)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at codechicken.core.asm.ClassHeirachyManager.transform(ClassHeirachyManager.java:80)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:178)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:133)
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE]   ... 34 more
2012-12-15 00:07:56 [INFO] [STDERR] 00:07:56 [SEVERE] Encountered an unexpected exception LoaderException
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: ModLoader
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:117)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:493)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:81)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:344)
    at ho.c(DedicatedServer.java:58)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
    at fy.run(SourceFile:856)
Caused by: java.lang.NoClassDefFoundError: ModLoader
    at com.github.AbrarSyed.SecretRooms.SecretRooms.addrecipes(SecretRooms.java:204)
    at com.github.AbrarSyed.SecretRooms.SecretRooms.load(SecretRooms.java:172)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:440)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at mcpc.com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at mcpc.com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at mcpc.com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at mcpc.com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at mcpc.com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at mcpc.com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at mcpc.com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at mcpc.com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at mcpc.com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at mcpc.com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: ModLoader
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:141)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 32 more
Caused by: java.lang.NullPointerException
    at org.objectweb.asm.ClassReader.<init>(Unknown Source)
    at codechicken.core.asm.ClassHeirachyManager.transform(ClassHeirachyManager.java:80)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:178)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:133)
    ... 34 more

**Comment by agaricusb** [comment]
Added ModLoader.class unmodified
Fixed in CPCM build 005 https://bitbucket.org/agaricusb/mcpc-1.4.5/downloads/cpcm-1.4.5-005.jar
https://github.com/agaricusb/MCPC-1.4.5/commit/7b2d31568e37b292065cfd7d174366a2dc146941

Secret Rooms Mod now works on CPCM
