### ISSUE TITLE
 Balkon's Weapon Mod: custom projectile entities broken: java.lang.IllegalArgumentException: Unknown entity at org.bukkit.craftbukkit.entity.CraftEntity.getEntity(CraftEntity.java:152) 

### ISSUE THREAD

**Issue by agaricusb** [agaricusb/MCPC-1.4.5#2]
CPCM build 002, crash when shooting a weapon in Balkon's Weapon Mod. 

From http://pastie.org/5514640#2

2012-12-12 07:45:37 [SEVERE] [ForgeModLoader] A critical server error occured handling a packet, kicking iv@3d76f7d3
java.lang.IllegalArgumentException: Unknown entity
  at org.bukkit.craftbukkit.entity.CraftEntity.getEntity(CraftEntity.java:152)
  at lq.getBukkitEntity(Entity.java:1399)
  at xv.addEntity(World.java:1038)
  at xv.d(World.java:1007)
  at weaponmod.item.ItemMusket.fire(ItemMusket.java:53)
  at weaponmod.item.ItemShooter.a(ItemShooter.java:160)
  at um.b(ItemStack.java:288)
  at qx.bO(EntityHuman.java:106)
  at iv.a(NetServerHandler.java:517)
  at ej.a(SourceFile:46)
  at cg.b(NetworkManager.java:289)
  at iv.d(NetServerHandler.java:123)
  at iw.b(ServerConnection.java:53)
  at ht.b(SourceFile:30)
  at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:637)
  at ho.r(DedicatedServer.java:228)
  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:531)
  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
  at fy.run(SourceFile:856)
2012-12-12 07:45:37 [INFO] [STDERR] 07:45:37 [WARNING] Failed to handle packet for dwi/81.201.60.162: java.lang.IllegalArgumentException: Unknown entity
java.lang.IllegalArgumentException: Unknown entity
  at org.bukkit.craftbukkit.entity.CraftEntity.getEntity(CraftEntity.java:152)
  at lq.getBukkitEntity(Entity.java:1399)
  at xv.addEntity(World.java:1038)
  at xv.d(World.java:1007)
  at weaponmod.item.ItemMusket.fire(ItemMusket.java:53)
  at weaponmod.item.ItemShooter.a(ItemShooter.java:160)
  at um.b(ItemStack.java:288)
  at qx.bO(EntityHuman.java:106)
  at iv.a(NetServerHandler.java:517)
  at ej.a(SourceFile:46)
  at cg.b(NetworkManager.java:289)
  at iv.d(NetServerHandler.java:123)
  at iw.b(ServerConnection.java:53)
  at ht.b(SourceFile:30)
  at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:637)
  at ho.r(DedicatedServer.java:228)
  at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:531)
  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
  at fy.run(SourceFile:856)

Appears to be lack of support for custom entities.

**Comment by agaricusb** [comment]
Noted on http://www.mcportcentral.co.za/index.php?topic=1432.msg23092#msg23092
Bugs yet :
- No Entity is working yet!! Fix very very³ soon

1.4.5 R2 port fixed - but in vanilla? Changes to mod required?

**Comment by agaricusb** [comment]
MCPC+ supersedes CPCM -- if this issue reproduces with the latest build of MCPC+ please file a new issue on MCPC+
