### ISSUE TITLE
Secret Rooms Mod, many others: cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: [Block subclass].setTextureFile

### ISSUE THREAD

**Issue by npdev453** [agaricusb/MCPC-1.4.5#4]
CPCM build 002
SecretRoomsMod-universal-4.4.0.144.zip

---- Minecraft Crash Report ----
// My bad.

Time: 12.12.12 19:11
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: com.github.AbrarSyed.SecretRooms.BlockCamoStair.setTextureFile(Ljava/lang/String;)Lamj;
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:117)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:493)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:81)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:344)
    at ho.c(DedicatedServer.java:58)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at fy.run(SourceFile:856)
Caused by: java.lang.NoSuchMethodError: com.github.AbrarSyed.SecretRooms.BlockCamoStair.setTextureFile(Ljava/lang/String;)Lamj;
    at com.github.AbrarSyed.SecretRooms.BlockCamoStair.<init>(BlockCamoStair.java:25)
    at com.github.AbrarSyed.SecretRooms.SecretRooms.load(SecretRooms.java:102)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:440)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at mcpc.com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at mcpc.com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at mcpc.com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at mcpc.com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at mcpc.com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:140)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at mcpc.com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:69)
    at mcpc.com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at mcpc.com.google.common.eventbus.EventBus.dispatch(EventBus.java:317)
    at mcpc.com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:300)
    at mcpc.com.google.common.eventbus.EventBus.post(EventBus.java:268)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:83)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:492)
    ... 5 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.4.5
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_03, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 5890110032 bytes (5617 MB) / 6318718976 bytes (6026 MB) up to 9589161984 bytes (9144 MB)
    JVM Flags: 2 total; -Xms6288M -Xmx10288M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: TreeGenerator, $Proxy3, $Proxy4, ...[com.github.AbrarSyed.SecretRooms.SecretRooms, CreativeTabCamo, PacketHandlerClient, ...], [com.google.common.base.Predicate, Function, Joiner, ...], [com.google.common.collect.Maps, BiMap, MapDifference, ...], [cpw.mods.fml.common.Loader, LoaderException, DuplicateModsFoundException, ...], [cpw.mods.fml.common.asm.FMLSanityChecker, MLDetectorClassVisitor, SideOnly], [cpw.mods.fml.common.asm.transformers.AccessTransformer, Modifier, MarkerTransformer, ...], [cpw.mods.fml.common.discovery.ModDiscoverer, ASMDataTable, ModCandidate, ...], [cpw.mods.fml.common.discovery.asm.ASMModParser, ModClassVisitor, ModMethodVisitor, ...], [cpw.mods.fml.common.event.FMLLoadEvent, FMLEvent, FMLStateEvent, ...], [cpw.mods.fml.common.functions.ModIdFunction], [cpw.mods.fml.common.modloader.BaseModProxy], [cpw.mods.fml.common.network.Player, FMLNetworkHandler, NetworkModHandler, ...], [cpw.mods.fml.common.registry.BlockProxy, ItemProxy, LanguageRegistry], [cpw.mods.fml.common.toposort.ModSortingException, ModSorter, DirectedGraph, ...], [cpw.mods.fml.common.versioning.ArtifactVersion, VersionParser, InvalidVersionSpecificationException, ...], [cpw.mods.fml.server.FMLServerHandler], [mcpc.com.google.common.base.Preconditions, Charsets, Splitter, ...], [mcpc.com.google.common.cache.CacheLoader, CacheBuilder, Cache, ...], [mcpc.com.google.common.collect.Multimap, ListMultimap, AbstractMultimap, ...], [mcpc.com.google.common.eventbus.EventBus, HandlerFindingStrategy, AnnotatedHandlerFinder, ...], [mcpc.com.google.common.hash.Hashing, HashFunction, AbstractStreamingHashFunction, ...], [mcpc.com.google.common.io.LineProcessor, Resources, InputSupplier, ...], [mcpc.com.google.common.primitives.Ints, UnsignedBytes], [mcpc.com.google.common.reflect.TypeCapture, TypeToken, SimpleTypeToken, ...], [mcpc.com.google.common.util.concurrent.UncheckedExecutionException, ExecutionError, MoreExecutors, ...], [net.minecraft.server.BaseMod, CrashReportCategory], [net.minecraftforge.common.IPlantable, IShearable, ISidedInventory, ...], [net.minecraftforge.event.Event, ListenerList, CommandEvent, ...], [net.minecraftforge.event.entity.EntityEvent, EntityJoinWorldEvent], [net.minecraftforge.event.entity.living.LivingEvent], [net.minecraftforge.event.entity.player.PlayerEvent, ArrowNockEvent, ArrowLooseEvent, ...], [net.minecraftforge.event.world.WorldEvent, Unload, Load, ...], [net.minecraftforge.oredict.OreDictionary, OreRegisterEvent, ShapedOreRecipe, ...], [net.minecraftforge.transformers.ForgeAccessTransformer, EventTransformer], [org.bukkit.BlockChangeDelegate, World, Server, ...], [org.bukkit.block.BlockFace, BlockState], [org.bukkit.command.CommandSender, RemoteConsoleCommandSender], [org.bukkit.configuration.serialization.ConfigurationSerializable], [org.bukkit.craftbukkit.Main, LoggerOutputStream], [org.bukkit.craftbukkit.inventory.CraftItemStack, CraftRecipe, CraftShapedRecipe, ...], [org.bukkit.craftbukkit.libs.jline.Terminal, TerminalSupport, UnsupportedTerminal, ...], [org.bukkit.craftbukkit.libs.jline.console.ConsoleReader, CursorBuffer, ConsoleKeys, ...], [org.bukkit.craftbukkit.libs.jline.console.completer.CompletionHandler, CandidateListCompletionHandler], [org.bukkit.craftbukkit.libs.jline.console.history.History, MemoryHistory], [org.bukkit.craftbukkit.libs.jline.internal.InputStreamReader, Configuration, Log], [org.bukkit.craftbukkit.libs.joptsimple.OptionException, OptionParser, OptionSpec, ...], [org.bukkit.craftbukkit.libs.joptsimple.internal.AbbreviationMap, ReflectionException, Reflection, ...], [org.bukkit.craftbukkit.libs.joptsimple.util.KeyValuePair], [org.bukkit.craftbukkit.potion.CraftPotionEffectType], [org.bukkit.craftbukkit.util.ServerShutdownThread, Waitable, TerminalConsoleHandler, ...], [org.bukkit.entity.EntityType, Entity], [org.bukkit.event.Event, Cancellable], [org.bukkit.event.block.BlockEvent, BlockFadeEvent, BlockGrowEvent, ...], [org.bukkit.event.entity.EntityEvent, EntityInteractEvent, EntityDamageEvent, ...], [org.bukkit.event.hanging.HangingEvent, HangingPlaceEvent], [org.bukkit.event.painting.PaintingEvent, PaintingPlaceEvent, PaintingBreakEvent, ...], [org.bukkit.event.player.PlayerEvent, PlayerInteractEvent, PlayerFishEvent], [org.bukkit.event.server.Packet, ServerEvent, MapInitializeEvent, ...], [org.bukkit.event.vehicle.VehicleEvent, VehicleCollisionEvent, VehicleBlockCollisionEvent, ...], [org.bukkit.event.world.WorldEvent, WorldInitEvent, WorldSaveEvent, ...], [org.bukkit.inventory.ItemStack, Recipe, ShapedRecipe, ...], [org.bukkit.map.MapView], [org.bukkit.material.MaterialData, Tree, Directional, ...], [org.bukkit.metadata.Metadatable], [org.bukkit.permissions.ServerOperator, Permissible], [org.bukkit.plugin.messaging.PluginMessageRecipient], [org.bukkit.potion.PotionEffectType, PotionEffectTypeWrapper], [org.objectweb.asm.ClassVisitor, ClassWriter, AnnotationVisitor, ...], [org.objectweb.asm.tree.ClassNode, AnnotationNode, FieldNode, ...]
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport:
java.lang.NullPointerException
    at org.bukkit.Bukkit.getName(Bukkit.java:67)
    at org.bukkit.craftbukkit.CraftCrashReport.call(CraftCrashReport.java:20)
    at l.a(SourceFile:74)
    at a.h(CrashReport.java:47)
    at a.<init>(CrashReport.java:34)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:475)
    at fy.run(SourceFile:856)

```
Profiler Position: N/A (disabled)
Is Modded: Definitely; Server brand changed to 'craftbukkit-cpcm'
Type: Dedicated Server (map_server.txt)
```

**Comment by agaricusb** [comment]
https://github.com/agaricusb/MCPC-1.4.5/commit/9abef6b50d801ef4ce289975093126bbe6d63cb7
Fixed in CPCM 004 https://bitbucket.org/agaricusb/mcpc-1.4.5/downloads/cpcm-1.4.5-004.jar

This particular error, affecting many mods, is now fixed, but Secret Rooms Mod now fails to load with a different error. Tracking separately: https://github.com/agaricusb/MCPC-1.4.5/issues/11
