### ISSUE TITLE
Mo' Creatures java.lang.AbstractMethodError: drzhark.mocreatures.MoCEntityGolem.writeSpawnData(Lmcpc/com/google/common/io/ByteArrayDataOutput;)V 

### ISSUE THREAD

**Issue by agaricusb** [agaricusb/MCPC-1.4.5#8]
CPCM build 002

mods/CustomMobSpawner 1.9.2.zip
mods/DrZharks MoCreatures Mod v4.3.1.zip
mods/EnderStorage 1.3.0.3.jar
mods/Forge_LegendaryBeastsAlpha1.4.4.0.zip
mods/Obsidiplates-1.1.0.2.zip
coremods/CodeChickenCore 0.6.14.jar

crash on user join:

mods [ObsidiPlates, LegendaryBeasts, MoCreatures]
2012-12-12 14:05:35 [INFO] [STDERR] 14:05:35 [INFO] agnitfom[/127.0.0.1:63386] logged in with entity id 434 at ([world] -242.17323039834727, 61.0, 306.51318100526987)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE] t: Ticking entity
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:620)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at ho.r(DedicatedServer.java:228)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:531)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at fy.run(SourceFile:856)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE] Caused by: java.lang.AbstractMethodError: drzhark.mocreatures.MoCEntityGolem.writeSpawnData(Lmcpc/com/google/common/io/ByteArrayDataOutput;)V
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at cpw.mods.fml.common.network.EntitySpawnPacket.generatePacket(EntitySpawnPacket.java:119)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at cpw.mods.fml.common.network.FMLPacket.makePacket(FMLPacket.java:75)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at cpw.mods.fml.common.network.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:365)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at is.b(EntityTrackerEntry.java:395)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at is.b(EntityTrackerEntry.java:305)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at ii.a(EntityTracker.java:196)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at iq.j_(EntityPlayer.java:188)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at xv.a(World.java:1517)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at in.a(WorldServer.java:554)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at xv.g(World.java:1477)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at xv.h(World.java:1333)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at in.h(WorldServer.java:450)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:616)
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE]   ... 4 more
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE] Encountered an unexpected exception t
t: Ticking entity
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:620)
    at ho.r(DedicatedServer.java:228)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:531)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
    at fy.run(SourceFile:856)
Caused by: java.lang.AbstractMethodError: drzhark.mocreatures.MoCEntityGolem.writeSpawnData(Lmcpc/com/google/common/io/ByteArrayDataOutput;)V
    at cpw.mods.fml.common.network.EntitySpawnPacket.generatePacket(EntitySpawnPacket.java:119)
    at cpw.mods.fml.common.network.FMLPacket.makePacket(FMLPacket.java:75)
    at cpw.mods.fml.common.network.FMLNetworkHandler.getEntitySpawningPacket(FMLNetworkHandler.java:365)
    at is.b(EntityTrackerEntry.java:395)
    at is.b(EntityTrackerEntry.java:305)
    at ii.a(EntityTracker.java:196)
    at iq.j_(EntityPlayer.java:188)
    at xv.a(World.java:1517)
    at in.a(WorldServer.java:554)
    at xv.g(World.java:1477)
    at xv.h(World.java:1333)
    at in.h(WorldServer.java:450)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:616)
    ... 4 more
2012-12-12 14:05:36 [INFO] [STDERR] 14:05:36 [SEVERE] This crash report has been saved to: /private/tmp/f2/./crash-reports/crash-2012-12-12_14.05.36-server.txt

**Comment by agaricusb** [comment]
MCPC+ supersedes CPCM -- if this issue reproduces with the latest build of MCPC+ please file a new issue on MCPC+
