### ISSUE TITLE
Portal Gun java.lang.NoSuchMethodError: eh.getPlayer()Lqx;

### ISSUE THREAD

**Issue by agaricusb** [agaricusb/MCPC-1.4.5#9]
CPCM build 002

mods/portalgun1.4.4v0.1_universal.zip

crash when add portal gun item to inventory

2012-12-12 14:28:45 [INFO] [ForgeModLoader] Forge Mod Loader version 4.5.2.459 for Minecraft 1.4.5 loading
2012-12-12 14:28:45 [INFO] [STDOUT] Adding Accesstransformer map: codechickencore_at.cfg
2012-12-12 14:28:47 [INFO] [STDOUT] 208 recipes
2012-12-12 14:28:47 [INFO] [STDOUT] 27 achievements
2012-12-12 14:28:47 [INFO] [STDERR] 14:28:47 [INFO] Starting minecraft server version 1.4.5
2012-12-12 14:28:47 [INFO] [ForgeModLoader] Attempting early MinecraftForge initialization
2012-12-12 14:28:47 [INFO] [STDERR] 14:28:47 [INFO] MinecraftForge v
2012-12-12 14:28:47 [INFO] [STDERR] 14:28:47 [INFO] 6.4.0.397
2012-12-12 14:28:47 [INFO] [STDERR] 14:28:47 [INFO]  Initialized

2012-12-12 14:28:47 [INFO] [ForgeModLoader] MinecraftForge v6.4.0.397 Initialized
2012-12-12 14:28:47 [INFO] [STDERR] 14:28:47 [INFO] Replaced 85 ore recipies
2012-12-12 14:28:47 [INFO] [ForgeModLoader] Completed early MinecraftForge initialization
2012-12-12 14:28:47 [INFO] [ForgeModLoader] Searching /private/tmp/f2/mods for mods
2012-12-12 14:28:48 [INFO] [ForgeModLoader] Forge Mod Loader has identified 9 mods to load
2012-12-12 14:28:48 [WARNING] [ForgeModLoader] Mod mod_CodeChickenCore has been disabled through configuration
2012-12-12 14:28:48 [INFO] [ForgeModLoader] Configured a dormant chunk cache size of 0
2012-12-12 14:28:48 [INFO] [ObsidiPlates] Config loaded from: /private/tmp/f2/config/ObsidiPlates.cfg
2012-12-12 14:28:48 [INFO] [STDERR] 14:28:48 [INFO] [Portal Gun 1.4.4v0.1] Loading properties.
2012-12-12 14:28:48 [INFO] [STDERR] 14:28:48 [INFO] [Portal Gun 1.4.4v0.1] Properties loaded.
2012-12-12 14:28:48 [INFO] [STDERR] 14:28:48 [INFO] Loading properties
2012-12-12 14:28:48 [INFO] [STDERR] 14:28:48 [INFO] Default game type: SURVIVAL
2012-12-12 14:28:48 [INFO] [STDERR] 14:28:48 [INFO] Generating keypair
2012-12-12 14:28:49 [INFO] [STDERR] 14:28:49 [INFO] Starting Minecraft server on *:25565
2012-12-12 14:28:49 [INFO] [STDERR] 14:28:49 [INFO] MSC is not loaded...
2012-12-12 14:28:49 [INFO] [STDERR] 14:28:49 [INFO] ProjectBench: Registered block id @ 700
2012-12-12 14:28:49 [INFO] [ForgeModLoader] Forge Mod Loader has successfully loaded 9 mods
2012-12-12 14:28:49 [INFO] [STDERR] 14:28:49 [INFO] This server is running CraftBukkit-CPCM version null (MC: 1.4.5) (Implementing API version Unknown-Version)
2012-12-12 14:28:49 [INFO] [STDERR] 14:28:49 [INFO] [WorldEdit] Loading WorldEdit v5.4.5
2012-12-12 14:28:49 [INFO] [STDERR] 14:28:49 [INFO] [WorldGuard] Loading WorldGuard v5.6.5
2012-12-12 14:28:50 [INFO] [STDERR] 14:28:50 [INFO] Preparing level "world"
2012-12-12 14:28:50 [INFO] [ForgeModLoader] Loading dimension 0 (world) (ho@fa07419)
2012-12-12 14:28:50 [INFO] [STDERR] 14:28:50 [INFO] [Portal Gun 1.4.4v0.1] Portal data does not exist for dimension 0!
2012-12-12 14:28:50 [INFO] [ForgeModLoader] Loading dimension -1 (world_nether) (ho@fa07419)
2012-12-12 14:28:50 [INFO] [STDERR] 14:28:50 [INFO] [Portal Gun 1.4.4v0.1] Portal data does not exist for dimension -1!
2012-12-12 14:28:50 [INFO] [ForgeModLoader] Loading dimension 1 (world_the_end) (ho@fa07419)
2012-12-12 14:28:50 [INFO] [STDERR] 14:28:50 [INFO] [Portal Gun 1.4.4v0.1] Portal data does not exist for dimension 1!
2012-12-12 14:28:50 [INFO] [STDERR] 14:28:50 [INFO] Preparing start region for level 0 (Seed: 5266221417251030860)
2012-12-12 14:28:50 [INFO] [STDERR] 14:28:50 [WARNING] Could not get information about this CraftBukkit version; perhaps you are running a custom one?: FileNotFoundException
2012-12-12 14:28:50 [INFO] [STDERR] 14:28:50 [INFO] Reloading Storage: 0|global. remote = false
2012-12-12 14:28:50 [INFO] [STDERR] 14:28:50 [INFO] Reloading Storage: 0|global. remote = false
2012-12-12 14:28:50 [INFO] [STDERR] 14:28:50 [INFO] Preparing start region for level 1 (Seed: 5266221417251030860)
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] Preparing start region for level 2 (Seed: 5266221417251030860)
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] Preparing spawn area: 0%
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] Preparing start region for level 3 (Seed: 5266221417251030860)
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldEdit] Enabling WorldEdit v5.4.5
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] WEPIF: Using the Bukkit Permissions API.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard] Enabling WorldGuard v5.6.5
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world) TNT ignition is PERMITTED.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world) Lighters are PERMITTED.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world) Lava fire is blocked.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world) Fire spread is UNRESTRICTED.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard] Loaded configuration for world 'world'
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world_nether) TNT ignition is PERMITTED.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world_nether) Lighters are PERMITTED.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world_nether) Lava fire is blocked.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world_nether) Fire spread is UNRESTRICTED.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard] Loaded configuration for world 'world_nether'
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world_the_end) TNT ignition is PERMITTED.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world_the_end) Lighters are PERMITTED.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world_the_end) Lava fire is blocked.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard](world_the_end) Fire spread is UNRESTRICTED.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard] Loaded configuration for world 'world_the_end'
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard] 0 regions loaded for 'world'
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard] 0 regions loaded for 'world_nether'
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [WorldGuard] 0 regions loaded for 'world_the_end'
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] Server permissions file permissions.yml is empty, ignoring it
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] Done (1.574s)! For help, type "help" or "?"
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] Attempting to load data from directory /private/tmp/f2/./world/beastData
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [WARNING] LegendaryBeast.dat file not found! Aborting Load
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [Portal Gun 1.4.4v0.1] Loading local properties.
2012-12-12 14:28:51 [INFO] [STDERR] 14:28:51 [INFO] [Portal Gun 1.4.4v0.1] Local properties loaded.
2012-12-12 14:28:54 [INFO] [STDERR] 14:28:54 [INFO] User Player connecting with mods [bau5_ProjectBench, ObsidiPlates, PortalGun, LegendaryBeasts]
2012-12-12 14:28:54 [INFO] [ForgeModLoader] User Player connecting with mods [bau5_ProjectBench, ObsidiPlates, PortalGun, LegendaryBeasts]
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [INFO] Player[/127.0.0.1:49374] logged in with entity id 205 at ([world] -230.1859801307635, 57.0, 245.63384532629814)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [INFO] [Portal Gun 1.4.4v0.1] Recieved client info from Player
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE] java.lang.NoSuchMethodError: eh.getPlayer()Lqx;
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at portalgun.common.core.MapPacketHandler.handle(MapPacketHandler.java:33)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at cpw.mods.fml.common.network.NetworkRegistry.handleTinyPacket(NetworkRegistry.java:348)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket131Packet(FMLNetworkHandler.java:419)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at iv.a(NetServerHandler.java:1648)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at da.a(SourceFile:41)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at cg.b(NetworkManager.java:289)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at iv.d(NetServerHandler.java:123)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at iw.b(ServerConnection.java:53)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at ht.b(SourceFile:30)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:637)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at ho.r(DedicatedServer.java:228)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:531)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE]   at fy.run(SourceFile:856)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE] Encountered an unexpected exception NoSuchMethodError
java.lang.NoSuchMethodError: eh.getPlayer()Lqx;
    at portalgun.common.core.MapPacketHandler.handle(MapPacketHandler.java:33)
    at cpw.mods.fml.common.network.NetworkRegistry.handleTinyPacket(NetworkRegistry.java:348)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket131Packet(FMLNetworkHandler.java:419)
    at iv.a(NetServerHandler.java:1648)
    at da.a(SourceFile:41)
    at cg.b(NetworkManager.java:289)
    at iv.d(NetServerHandler.java:123)
    at iw.b(ServerConnection.java:53)
    at ht.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:637)
    at ho.r(DedicatedServer.java:228)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:531)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:457)
    at fy.run(SourceFile:856)
2012-12-12 14:28:55 [INFO] [STDERR] 14:28:55 [SEVERE] This crash report has been saved to: /private/tmp/f2/./crash-reports/crash-2012-12-12_14.28.55-server.txt

Remapping error?

**Comment by agaricusb** [comment]
MCPC+ supersedes CPCM -- if this issue reproduces with the latest build of MCPC+ please file a new issue on MCPC+
